
const SUPABASE_URL='https://mkefkbrffsxumhrmgllq.supabase.co';
const SUPABASE_KEY='sb_publishable_sLBhFLdi012jp6a2koA3XQ_rMoF4BEl';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id); const peso=n=>'₱'+Number(n||0).toLocaleString('en-PH',{maximumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let currentUser=null,currentHousehold=null,members=[];let data={transactions:[],goals:[],movements:[],properties:[],investments:[],debts:[],budgets:[]};let authMode='signin';
function msg(el,text,type='error'){el.innerHTML=text?`<div class="${type}">${esc(text)}</div>`:''}
function openModal(id){$(id).classList.add('show')}function closeModal(id){$(id).classList.remove('show')}window.openModal=openModal;window.closeModal=closeModal;
function nav(screen){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(screen).classList.add('active');document.querySelectorAll('#nav button[data-screen]').forEach(x=>x.classList.toggle('active',x.dataset.screen===screen));if(screen==='more')renderMore();if(screen==='reports')renderReport()}window.nav=nav;
document.querySelectorAll('#nav button[data-screen]').forEach(b=>b.onclick=()=>nav(b.dataset.screen));
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session){showAuth();return}currentUser=session.user;await loadHousehold()}
function showAuth(){$('authView').classList.remove('hide');$('householdView').classList.add('hide');$('appView').classList.add('hide');$('nav').classList.add('hide')}
function showHousehold(){$('authView').classList.add('hide');$('householdView').classList.remove('hide');$('appView').classList.add('hide');$('nav').classList.add('hide')}
async function showApp(){$('authView').classList.add('hide');$('householdView').classList.add('hide');$('appView').classList.remove('hide');$('nav').classList.remove('hide');await refreshAll();subscribeRealtime()}
$('authToggle').onclick=()=>{authMode=authMode==='signin'?'signup':'signin';$('authTitle').textContent=authMode==='signin'?'Sign in':'Create account';$('authSubmit').textContent=authMode==='signin'?'Sign in':'Create account';$('authToggle').textContent=authMode==='signin'?'Create an account':'I already have an account';msg($('authMsg'),'')};
$('authSubmit').onclick=async()=>{const email=$('authEmail').value.trim(),password=$('authPassword').value;if(!email||password.length<6){msg($('authMsg'),'Enter a valid email and a password with at least 6 characters.');return}msg($('authMsg'),'');if(authMode==='signup'){const {data:r,error}=await sb.auth.signUp({email,password});if(error){msg($('authMsg'),error.message);return}if(!r.session){msg($('authMsg'),'Account created. Check your email for the confirmation link, then return here and sign in.','success');authMode='signin';$('authSubmit').textContent='Sign in';$('authTitle').textContent='Sign in';return}currentUser=r.user;await loadHousehold()}else{const {data:r,error}=await sb.auth.signInWithPassword({email,password});if(error){msg($('authMsg'),error.message);return}currentUser=r.user;await loadHousehold()}};
async function loadHousehold(){
 const {data:r,error}=await sb.rpc('get_my_household');
 if(error){console.error(error);msg($('houseMsg'),error.message);showHousehold();return}
 const row=Array.isArray(r)?r[0]:r;
 if(!row){showHousehold();return}
 currentHousehold={id:row.household_id,name:row.household_name,invite_code:row.invite_code};
 await showApp()
}
$('createHouse').onclick=async()=>{
 const btn=$('createHouse'); if(btn.disabled)return; btn.disabled=true; btn.textContent='Checking...'; msg($('houseMsg'),'');
 try{
  const {data:existing,error:lookupError}=await sb.rpc('get_my_household');
  if(lookupError){msg($('houseMsg'),lookupError.message);return}
  const row=Array.isArray(existing)?existing[0]:existing;
  if(row){currentHousehold={id:row.household_id,name:row.household_name,invite_code:row.invite_code};await showApp();return}
  btn.textContent='Creating...';
  const {error}=await sb.rpc('create_household',{household_name:$('houseName').value.trim()||'Malama Journey',member_name:$('createName').value.trim()||'Anna'});
  if(error){msg($('houseMsg'),error.message);return}
  await loadHousehold();
 }finally{btn.disabled=false;btn.textContent='Create household'}
};
$('joinHouse').onclick=async()=>{const btn=$('joinHouse');if(btn.disabled)return;msg($('houseMsg'),'');const code=$('joinCode').value.trim();if(!code){msg($('houseMsg'),'Enter the household invite code.');return}btn.disabled=true;btn.textContent='Joining...';try{const {error}=await sb.rpc('join_household',{household_invite_code:code,member_name:$('joinName').value.trim()||'Member'});if(error){msg($('houseMsg'),error.message);return}await loadHousehold()}finally{btn.disabled=false;btn.textContent='Join household'}};
$('signOutSetup').onclick=async()=>{await sb.auth.signOut();location.reload()};$('signOut').onclick=async()=>{await sb.auth.signOut();location.reload()};
async function refreshAll(){if(!currentHousehold)return;const hid=currentHousehold.id;const [tx,g,m,p,i,d,b,mem]=await Promise.all([
 sb.from('transactions').select('*').eq('household_id',hid).order('transaction_date',{ascending:false}).order('created_at',{ascending:false}),
 sb.from('savings_goals').select('*').eq('household_id',hid).order('created_at',{ascending:false}),
 sb.from('savings_movements').select('*').eq('household_id',hid).order('movement_date',{ascending:false}),
 sb.from('properties').select('*').eq('household_id',hid).order('created_at',{ascending:false}),
 sb.from('investments').select('*').eq('household_id',hid).order('created_at',{ascending:false}),
 sb.from('debts').select('*').eq('household_id',hid).order('created_at',{ascending:false}),
 sb.from('budgets').select('*').eq('household_id',hid).order('created_at',{ascending:false}),
 sb.from('household_members').select('display_name,role,user_id').eq('household_id',hid)
 ]);const errs=[tx,g,m,p,i,d,b,mem].filter(x=>x.error);if(errs.length){console.error(errs.map(x=>x.error));}
 data={transactions:tx.data||[],goals:g.data||[],movements:m.data||[],properties:p.data||[],investments:i.data||[],debts:d.data||[],budgets:b.data||[]};members=mem.data||[];renderAll()}
window.refreshAll=refreshAll;
function monthTx(){const now=new Date();return data.transactions.filter(t=>{const d=new Date(t.transaction_date+'T00:00:00');return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()})}
function goalBalance(g){return Number(g.current_balance||0)+data.movements.filter(m=>m.goal_id===g.id).reduce((s,m)=>s+Number(m.amount||0),0)}
function goalIcon(t){return t==='Travel Fund'?'✈️':t==='Emergency Fund'?'🛟':t==='Home / Property Fund'?'🏠':t==='Gifts / Holidays'?'🎁':t==='General Savings'?'💰':'🎯'}
function renderHome(){const tx=monthTx(),inc=tx.filter(x=>x.transaction_type==='income').reduce((s,x)=>s+Number(x.amount),0),exp=tx.filter(x=>x.transaction_type==='expense').reduce((s,x)=>s+Number(x.amount),0),net=inc-exp,goalTotal=data.goals.reduce((s,g)=>s+goalBalance(g),0),propValue=data.properties.reduce((s,p)=>s+Number(p.current_value||0),0),propLoan=data.properties.reduce((s,p)=>s+Number(p.loan_balance||0),0),inv=data.investments.reduce((s,i)=>s+Number(i.current_value||0),0),debt=data.debts.reduce((s,d)=>s+Number(d.current_balance||0),0);$('incomeTotal').textContent=peso(inc);$('expenseTotal').textContent=peso(exp);$('netTotal').textContent=peso(net);$('saveBar').style.width=Math.max(0,Math.min(100,inc?net/inc*100:0))+'%';$('goalHomeTotal').textContent=peso(goalTotal);$('goalHomeSummary').textContent=data.goals.length?`${data.goals.length} active savings goal${data.goals.length===1?'':'s'}`:'Travel, emergency fund and more';$('goalHomeList').innerHTML=data.goals.slice(0,2).map(g=>`<div class="item"><div class="left"><div class="ico">${goalIcon(g.goal_type)}</div><div><b>${esc(g.name)}</b><div class="small">${peso(goalBalance(g))} of ${peso(g.target_amount)}</div></div></div></div>`).join('');$('propertyEquity').textContent=peso(propValue-propLoan);$('investmentTotal').textContent=peso(inv);$('debtTotal').textContent='-'+peso(debt)}
function renderTransactions(filter='all'){const list=data.transactions.filter(t=>filter==='all'||t.transaction_type===filter);$('txList').innerHTML=list.length?list.map(t=>`<div class="item"><div style="width:100%"><div class="top"><div class="left"><div class="ico">${t.transaction_type==='income'?'💰':t.transaction_type==='expense'?'🧾':'↔️'}</div><div><b>${esc(t.description)}</b><div class="small">${esc(t.category||t.transaction_type)} • ${esc(t.person||'Shared')} • ${esc(t.transaction_date)}</div></div></div><div class="amount ${t.transaction_type==='expense'?'neg':''}">${t.transaction_type==='expense'?'-':t.transaction_type==='income'?'+':''}${peso(t.amount)}</div></div><div class="mini-actions"><button onclick="editTransaction('${t.id}')">Edit</button><button class="danger" onclick="deleteTransaction('${t.id}')">Delete</button></div></div></div>`).join(''):'<div class="empty">No transactions yet.</div>'}window.renderTransactions=renderTransactions;
function renderGoals(){const total=data.goals.reduce((s,g)=>s+goalBalance(g),0);$('savingsTotal').textContent=peso(total);$('savingsGoalCount').textContent=data.goals.length?`${data.goals.length} savings goal${data.goals.length===1?'':'s'}`:'No goals yet';$('savingsList').innerHTML=data.goals.length?data.goals.map(g=>{const bal=goalBalance(g),pct=Math.min(100,Number(g.target_amount)?bal/Number(g.target_amount)*100:0);return `<div class="card" style="margin-top:10px"><div class="top"><div class="left"><div class="ico">${goalIcon(g.goal_type)}</div><div><b>${esc(g.name)}</b><div class="small">${esc(g.goal_type)} • ${esc(g.owner_name)}</div></div></div><span class="tag">${Math.round(pct)}%</span></div><div class="item"><b>${peso(bal)}</b><span class="small">Goal ${peso(g.target_amount)}</span></div><div class="bar"><div class="fill" style="width:${pct}%"></div></div><button class="pill" style="margin-top:12px" onclick="openContribution('${g.id}')">+ Add money</button></div>`}).join(''):'<div class="card empty">No savings goals yet.</div>'}
function renderGrow(){const propValue=data.properties.reduce((s,p)=>s+Number(p.current_value||0),0),propLoan=data.properties.reduce((s,p)=>s+Number(p.loan_balance||0),0),inv=data.investments.reduce((s,i)=>s+Number(i.current_value||0),0);$('propertyList').innerHTML=data.properties.length?data.properties.map(p=>`<div class="item"><div style="width:100%"><div class="left"><div><b>${esc(p.name)}</b><div class="small">${esc(p.property_type||'Property')} • ${esc(p.ownership)} • ${esc(p.status||'')}</div><div class="small">Equity ${peso(Number(p.current_value||0)-Number(p.loan_balance||0))}${Number(p.rental_income||0)?` • Rent ${peso(p.rental_income)}/mo`:''}</div>${p.payment_due_day?`<div class="due">Payment due day ${p.payment_due_day}${p.payment_cutoff_time?` • Pay by ${formatTime(p.payment_cutoff_time)}`:''}</div>`:''}</div><div class="amount">${peso(p.current_value)}</div></div><div class="mini-actions"><button onclick="editProperty('${p.id}')">Edit</button><button class="danger" onclick="deleteProperty('${p.id}')">Delete</button></div></div></div>`).join(''):'<div class="empty">No properties yet.</div>';$('investmentList').innerHTML=data.investments.length?data.investments.map(i=>`<div class="item"><div><b>${esc(i.name)}</b><div class="small">${esc(i.symbol||i.investment_type||'Investment')} • ${esc(i.ownership)}</div><div class="small">Contributed ${peso(i.total_contributions)}</div></div><div class="amount">${peso(i.current_value)}</div></div>`).join(''):'<div class="empty">No investments yet.</div>'}
function formatTime(t){if(!t)return'';const [h,m]=String(t).split(':');let hr=Number(h),ampm=hr>=12?'PM':'AM';hr=hr%12||12;return `${hr}:${m||'00'} ${ampm}`}
function renderDebts(){const total=data.debts.reduce((s,d)=>s+Number(d.current_balance||0),0);$('debtPageTotal').textContent=peso(total);$('debtList').innerHTML=data.debts.length?data.debts.map(d=>`<div class="item"><div style="width:100%"><div class="left"><div><b>${esc(d.name)}</b><div class="small">${esc(d.debt_type||'Debt')} • ${esc(d.ownership||'Shared')}</div><div class="small">${peso(d.monthly_payment||0)}/month${d.due_day?` • due day ${d.due_day}`:''}</div>${d.payment_cutoff_time?`<div class="due">Pay by ${formatTime(d.payment_cutoff_time)}</div>`:''}${d.statement_date?`<div class="due">Statement day ${d.statement_date}${Number(d.credit_limit||0)?` • Limit ${peso(d.credit_limit)}`:''}</div>`:''}</div><div class="amount neg">-${peso(d.current_balance)}</div></div><div class="mini-actions"><button onclick="editDebt('${d.id}')">Edit</button><button class="danger" onclick="deleteDebt('${d.id}')">Delete</button></div></div></div>`).join(''):'<div class="empty">No debts yet.</div>'}
function renderMore(){$('inviteCode').textContent=currentHousehold?.invite_code||'—';$('memberText').textContent=members.length?members.map(m=>m.display_name||'Member').join(' • '):'';renderBudgets()}
function renderAll(){renderHome();renderTransactions();renderGoals();renderGrow();renderDebts();renderMore();renderDueAlerts();checkCardReminders()}
window.openContribution=id=>{const g=data.goals.find(x=>x.id===id);if(!g)return;$('contribGoal').innerHTML=`<option value="${g.id}">${esc(g.name)}</option>`;openModal('contributeModal')};
$('saveTx').onclick=async()=>{const amount=Number($('txAmount').value);if(!$('txDesc').value.trim()||!amount)return alert('Enter a description and amount.');const id=$('txEditId').value;const payload={transaction_type:$('txType').value,description:$('txDesc').value.trim(),category:$('txCategory').value,person:$('txPerson').value,amount,transaction_date:$('txDate').value||new Date().toISOString().slice(0,10),payment_method:$('txPaymentMethod').value||null,account_name:$('txAccount').value.trim()||null,notes:$('txNotes').value.trim()||null,updated_by:currentUser.id};let q;if(id){q=sb.from('transactions').update(payload).eq('id',id)}else{q=sb.from('transactions').insert({...payload,household_id:currentHousehold.id,created_by:currentUser.id,source:'manual'})}const {error}=await q;if(error)return alert(error.message);closeModal('txModal');clearTxForm();await refreshAll()};
function clearTxForm(){$('txEditId').value='';$('txDesc').value='';$('txAmount').value='';$('txDate').value=new Date().toISOString().slice(0,10);$('txPaymentMethod').value='';$('txAccount').value='';$('txNotes').value='';$('txModalTitle').textContent='Add transaction';$('saveTx').textContent='Save transaction'}
window.editTransaction=id=>{const t=data.transactions.find(x=>x.id===id);if(!t)return;$('txEditId').value=t.id;$('txType').value=t.transaction_type||'expense';$('txDesc').value=t.description||'';$('txAmount').value=t.amount||0;$('txDate').value=t.transaction_date||new Date().toISOString().slice(0,10);$('txPerson').value=t.person||'Shared';$('txCategory').value=t.category||'Other';$('txPaymentMethod').value=t.payment_method||'';$('txAccount').value=t.account_name||'';$('txNotes').value=t.notes||'';$('txModalTitle').textContent='Edit transaction';$('saveTx').textContent='Update transaction';openModal('txModal')};
window.deleteTransaction=async id=>{if(!confirm('Delete this transaction? This will update your monthly reports too.'))return;const {error}=await sb.from('transactions').delete().eq('id',id);if(error)return alert(error.message);await refreshAll()};
$('saveGoal').onclick=async()=>{const target=Number($('goalTarget').value),start=Number($('goalBalance').value)||0;if(!target)return alert('Enter a target amount.');const name=$('goalName').value.trim()||$('goalType').value;const {error}=await sb.from('savings_goals').insert({household_id:currentHousehold.id,created_by:currentUser.id,name,goal_type:$('goalType').value,owner_name:$('goalOwner').value,target_amount:target,current_balance:start,target_date:$('goalDate').value||null});if(error)return alert(error.message);closeModal('goalModal');await refreshAll()};
$('saveContribution').onclick=async()=>{const amount=Number($('contribAmount').value),goal_id=$('contribGoal').value;if(!amount)return alert('Enter an amount.');const {error}=await sb.from('savings_movements').insert({household_id:currentHousehold.id,goal_id,created_by:currentUser.id,amount,movement_date:new Date().toISOString().slice(0,10),note:$('contribNote').value.trim()||null});if(error)return alert(error.message);$('contribAmount').value='';$('contribNote').value='';closeModal('contributeModal');await refreshAll()};
$('saveProperty').onclick=async()=>{if(!$('propName').value.trim())return alert('Enter a property name.');const payload={household_id:currentHousehold.id,created_by:currentUser.id,name:$('propName').value.trim(),location:$('propLocation').value.trim()||null,property_type:$('propType').value,ownership:$('propOwner').value,status:$('propStatus').value,purchase_price:Number($('propPurchase').value)||0,current_value:Number($('propValue').value)||0,loan_balance:Number($('propLoan').value)||0,monthly_payment:Number($('propPayment').value)||0,payment_due_day:Number($('propDue').value)||null,payment_cutoff_time:$('propCutoff').value||null,rental_income:Number($('propRent').value)||0};const id=$('propEditId').value;let q=id?sb.from('properties').update(payload).eq('id',id):sb.from('properties').insert(payload);const {error}=await q;if(error)return alert(error.message);closeModal('propertyModal');clearPropertyForm();await refreshAll()};
function clearPropertyForm(){['propEditId','propName','propLocation','propPurchase','propValue','propLoan','propPayment','propDue','propCutoff','propRent'].forEach(id=>$(id).value='');$('propertyModalTitle').textContent='Add property';$('saveProperty').textContent='Save property'}
window.editProperty=id=>{const p=data.properties.find(x=>x.id===id);if(!p)return;$('propEditId').value=p.id;$('propName').value=p.name||'';$('propLocation').value=p.location||'';$('propType').value=p.property_type||'Condo';$('propOwner').value=p.ownership||'Shared';$('propStatus').value=p.status||'RFO';$('propPurchase').value=p.purchase_price||0;$('propValue').value=p.current_value||0;$('propLoan').value=p.loan_balance||0;$('propPayment').value=p.monthly_payment||0;$('propDue').value=p.payment_due_day||'';$('propCutoff').value=p.payment_cutoff_time?String(p.payment_cutoff_time).slice(0,5):'';$('propRent').value=p.rental_income||0;$('propertyModalTitle').textContent='Edit property';$('saveProperty').textContent='Update property';openModal('propertyModal')};
window.deleteProperty=async id=>{if(!confirm('Delete this property?'))return;const {error}=await sb.from('properties').delete().eq('id',id);if(error)return alert(error.message);await refreshAll()};
$('saveInvestment').onclick=async()=>{if(!$('invName').value.trim())return alert('Enter an investment name.');const {error}=await sb.from('investments').insert({household_id:currentHousehold.id,created_by:currentUser.id,name:$('invName').value.trim(),symbol:$('invSymbol').value.trim()||null,investment_type:'Stocks',ownership:$('invOwner').value,total_contributions:Number($('invContribution').value)||0,current_value:Number($('invValue').value)||0});if(error)return alert(error.message);closeModal('investmentModal');await refreshAll()};
$('saveDebt').onclick=async()=>{if(!$('debtName').value.trim())return alert('Enter a debt name.');const bal=Number($('debtBalance').value)||0;const id=$('debtEditId').value;const common={household_id:currentHousehold.id,created_by:currentUser.id,name:$('debtName').value.trim(),debt_type:$('debtType').value,ownership:$('debtOwner').value,current_balance:bal,monthly_payment:Number($('debtPayment').value)||0,due_day:Number($('debtDue').value)||null,payment_cutoff_time:$('debtCutoff').value||null,statement_date:Number($('debtStatement').value)||null,credit_limit:Number($('debtLimit').value)||null,interest_rate:Number($('debtRate').value)||null,reminder_enabled:$('debtReminderEnabled').checked,reminder_days_before:Number($('debtReminderDays').value)||3};const payload=id?common:{...common,original_balance:bal};let q=id?sb.from('debts').update(payload).eq('id',id):sb.from('debts').insert(payload);const {error}=await q;if(error)return alert(error.message);closeModal('debtModal');clearDebtForm();await refreshAll()};
function clearDebtForm(){['debtEditId','debtName','debtBalance','debtPayment','debtDue','debtCutoff','debtStatement','debtLimit','debtRate'].forEach(id=>$(id).value='');$('debtReminderDays').value='3';$('debtReminderEnabled').checked=true;$('debtModalTitle').textContent='Add debt or credit card';$('saveDebt').textContent='Save debt'}
window.editDebt=id=>{const d=data.debts.find(x=>x.id===id);if(!d)return;$('debtEditId').value=d.id;$('debtName').value=d.name||'';$('debtType').value=d.debt_type||'Credit Card';$('debtBalance').value=d.current_balance||0;$('debtPayment').value=d.monthly_payment||0;$('debtDue').value=d.due_day||'';$('debtCutoff').value=d.payment_cutoff_time?String(d.payment_cutoff_time).slice(0,5):'';$('debtStatement').value=d.statement_date||'';$('debtLimit').value=d.credit_limit||'';$('debtRate').value=d.interest_rate||'';$('debtReminderDays').value=String(d.reminder_days_before||3);$('debtReminderEnabled').checked=d.reminder_enabled!==false;$('debtOwner').value=d.ownership||'Shared';$('debtModalTitle').textContent='Edit debt or credit card';$('saveDebt').textContent='Update debt';openModal('debtModal')};
window.deleteDebt=async id=>{if(!confirm('Delete this debt or credit card?'))return;const {error}=await sb.from('debts').delete().eq('id',id);if(error)return alert(error.message);await refreshAll()};
$('saveBudget').onclick=async()=>{const category=$('budgetCategory').value.trim(),limit=Number($('budgetLimit').value);if(!category||!limit)return alert('Enter a category and limit.');const {error}=await sb.from('budgets').insert({household_id:currentHousehold.id,created_by:currentUser.id,category,monthly_limit:limit,owner_name:$('budgetOwner').value});if(error)return alert(error.message);closeModal('budgetModal');await refreshAll()};
let reportScope='Anna';
function initReportMonth(){if(!$('reportMonth').value)$('reportMonth').value=new Date().toISOString().slice(0,7)}
window.setReportScope=scope=>{reportScope=scope;document.querySelectorAll('.report-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.scope===scope));renderReport()};
window.shiftReportMonth=n=>{initReportMonth();const [y,m]=$('reportMonth').value.split('-').map(Number);const d=new Date(y,m-1+n,1);$('reportMonth').value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;renderReport()};
async function renderReport(){if(!currentHousehold)return;initReportMonth();const month=$('reportMonth').value+'-01';$('reportContent').innerHTML='<div class="card empty">Loading report…</div>';const {data:r,error}=await sb.rpc('get_monthly_report',{p_household_id:currentHousehold.id,p_month:month,p_scope:reportScope});if(error){$('reportContent').innerHTML=`<div class="card"><div class="error">${esc(error.message)}</div></div>`;return}const cats=(r.category_breakdown||[]).map(c=>`<div class="report-row"><span>${esc(c.category)}</span><b>${peso(c.amount)}</b></div>`).join('')||'<div class="empty">No expenses for this month.</div>';$('reportContent').innerHTML=`<div class="card"><div class="eyebrow">${esc(reportScope)} • ${esc(r.month)}</div><div class="report-grid" style="margin-top:10px"><div class="metric green"><div class="label">Income</div><div class="value">${peso(r.income)}</div></div><div class="metric red"><div class="label">Expenses</div><div class="value">${peso(r.expenses)}</div></div></div><div class="report-row" style="margin-top:10px"><span>Net cash flow</span><b>${peso(r.net_cash_flow)}</b></div><div class="report-row"><span>Savings contributions</span><b>${peso(r.savings_contributions)}</b></div><div class="report-row"><span>Investment contributions</span><b>${peso(r.investment_contributions)}</b></div><div class="report-row"><span>Debt/card payments</span><b>${peso(r.debt_payments)}</b></div></div><div class="section-title">Spending by category</div><div class="card">${cats}</div><div class="section-title">Where you stand now</div><div class="card"><div class="report-row"><span>Savings balance</span><b>${peso(r.current_savings_balance)}</b></div><div class="report-row"><span>Investment value</span><b>${peso(r.current_investment_value)}</b></div><div class="report-row"><span>Debt balance</span><b>${peso(r.current_debt_balance)}</b></div><div class="report-row"><span>Property value</span><b>${peso(r.property_value)}</b></div><div class="report-row"><span>Property equity</span><b>${peso(r.property_equity)}</b></div></div>`}
window.renderReport=renderReport;
function nextCardDueDate(day){const now=new Date();let d=new Date(now.getFullYear(),now.getMonth(),Math.min(Number(day),new Date(now.getFullYear(),now.getMonth()+1,0).getDate()),12,0,0);if(d<new Date(now.getFullYear(),now.getMonth(),now.getDate(),0,0,0)){const y=now.getMonth()===11?now.getFullYear()+1:now.getFullYear(),m=(now.getMonth()+1)%12;d=new Date(y,m,Math.min(Number(day),new Date(y,m+1,0).getDate()),12,0,0)}return d}
function cardDueInfo(d){if(!d.due_day)return null;const due=nextCardDueDate(d.due_day),today=new Date();today.setHours(0,0,0,0);const cmp=new Date(due);cmp.setHours(0,0,0,0);const days=Math.round((cmp-today)/86400000);return {due,days}}
function renderDueAlerts(){if(!$('dueAlerts'))return;const cards=data.debts.filter(d=>String(d.debt_type||'').toLowerCase()==='credit card'&&d.due_day&&d.reminder_enabled!==false).map(d=>({d,info:cardDueInfo(d)})).filter(x=>x.info&&x.info.days>=0&&x.info.days<=Number(x.d.reminder_days_before||3));$('dueAlerts').innerHTML=cards.length?`<div class="card" style="margin-top:12px;background:#fff8e7"><b>💳 Card deadlines</b>${cards.map(({d,info})=>`<div class="due" style="margin-top:7px">${esc(d.name)}: due ${info.due.toLocaleDateString('en-PH',{month:'short',day:'numeric'})}${d.payment_cutoff_time?` by ${formatTime(d.payment_cutoff_time)}`:''} (${info.days===0?'today':info.days+' day'+(info.days===1?'':'s')+' left'})</div>`).join('')}</div>`:''}
async function requestCardReminders(){if(!('Notification' in window)){alert('Notifications are not supported in this browser. Add Mālama Journey to your iPhone Home Screen and try again.');return}const permission=await Notification.requestPermission();localStorage.setItem('malama-card-reminders',permission==='granted'?'on':'off');updateReminderStatus();if(permission==='granted')checkCardReminders(true)}window.requestCardReminders=requestCardReminders;
function updateReminderStatus(){if(!$('reminderStatus'))return;const supported='Notification' in window,enabled=supported&&Notification.permission==='granted'&&localStorage.getItem('malama-card-reminders')==='on';$('reminderStatus').textContent=enabled?'Reminders enabled on this device. Each household member must enable them on their own phone.':supported?'Reminders are off on this device.':'Browser notifications are not available here.';if($('enableReminders'))$('enableReminders').textContent=enabled?'Reminders enabled ✓':'Enable reminders on this device'}
async function checkCardReminders(force=false){renderDueAlerts();updateReminderStatus();if(!('Notification' in window)||Notification.permission!=='granted'||localStorage.getItem('malama-card-reminders')!=='on')return;const reg=await navigator.serviceWorker?.ready.catch(()=>null);for(const d of data.debts){if(String(d.debt_type||'').toLowerCase()!=='credit card'||!d.due_day||d.reminder_enabled===false)continue;const info=cardDueInfo(d),lead=Number(d.reminder_days_before||3);if(!info||info.days<0||info.days>lead)continue;const key=`malama-card-reminder-${d.id}-${info.due.toISOString().slice(0,10)}`;if(!force&&localStorage.getItem(key))continue;const title=`${d.name} payment due ${info.days===0?'today':'soon'}`;const body=`Due ${info.due.toLocaleDateString('en-PH',{month:'short',day:'numeric'})}${d.payment_cutoff_time?` by ${formatTime(d.payment_cutoff_time)}`:''}. Balance: ${peso(d.current_balance||0)}.`;try{if(reg)await reg.showNotification(title,{body,tag:key,icon:'icon-192.svg'});else new Notification(title,{body,tag:key});localStorage.setItem(key,'1')}catch(e){console.warn('Reminder notification failed',e)}}}
let channel=null;function subscribeRealtime(){if(channel)sb.removeChannel(channel);channel=sb.channel('malama-'+currentHousehold.id).on('postgres_changes',{event:'*',schema:'public',filter:`household_id=eq.${currentHousehold.id}`},()=>refreshAll()).subscribe()}
sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')showAuth()});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&currentHousehold)refreshAll()});
$('reportMonth').addEventListener('change',renderReport);clearTxForm();updateReminderStatus();boot();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
